### ISSUE TITLE
netbox: not possible to omit externalDatabase password

### ISSUE THREAD

**Issue by norman-zon** [startechnica/apps#63]
Using the netbox chart 5.0.7 it is not possible to omit `existingSecretPasswordKey`.

I use Google CloudSQL with IAM based auth (via CloudSQL proxy), which does not need a password.

When setting the connection info like this, everything works:

```yaml
externalDatabase:
    host: localhost
    port: 5432
    database: netbox
    username: "serviceaccount@project.iam"
    password: ""
```

But when I try to use an existing secret with an empty password like so:

```yaml
externalDatabase:
    existingSecretName: cloudsql-proxy-iam
    existingSecretHostKey: PGHOST
    existingSecretPortKey: PGPORT
    existingSecretUserKey: PGUSER
    existingSecretDatabaseKey: PGDATABASE
    existingSecretPasswordKey: PGPASSWORD
```

I get: 

```sh
django.db.utils.OperationalError: connection failed: fe_sendauth: no password supplied
```

If I remove `existingSecretPasswordKey` completely, the chart fails with:

```
MountVolume.SetUp failed for volume "secrets" : references non-existent secret key: db-password
```

I think my usecase is not super common, but viable. Could you please change the handling of `existingSecretPasswordKey`, so it can be omited?
