### ISSUE TITLE
netbox: How is externalRedis utilized?

### ISSUE THREAD

**Issue by qgervacio** [startechnica/apps#65]
Hi,

I would like to ask how many external redis db the config requires or recommends?

```yaml
tasksRedis:
cachingRedis:
externalRedis:
```
