### ISSUE TITLE
netbox: .Values.image is not respected

### ISSUE THREAD

**Issue by norman-zon** [startechnica/apps#83]
When setting `.Values.image.X` in my [values.yaml](https://github.com/startechnica/apps/blob/574aa1c6345e6a5fb9c504dd4f1d5763848c5459/charts/netbox/values.yaml#L101) the values are not used in the deployment.

Changing it in `.Values.global` works though. But I only need to overwrite the image for the deployment, not for all components.

MWE:
 
```yaml
image:
  registry: europe-west3-docker.pkg.dev
  repository: my-comp/docker/netbox
  tag: latest
```

results in:

```yaml
containers:
  - name: netbox
     image: docker.io/netboxcommunity/netbox:v3.7.8-2.8.0
```
